# k8s cluster in existing VPC
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ran-eks
  region: ap-south-1

vpc:
  id: "vpc-03cc59da9849f3b8c"  
  subnets:
    public:
      ap-south-1a: { id: subnet-0ee99eed8ae5b6b15 } 
      ap-south-1b: { id: subnet-0464b9b3fd5fd36e1 }
    private:
      ap-south-1a: { id: subnet-0e5e4f2133742957f}
      ap-south-1b: { id: subnet-0c54dc5b16855fe79}

nodeGroups:
  - name: worker-1
    instanceType: t2.micro
    desiredCapacity: 1
  